version: "3.8"

services:
  api:
    build:
      dockerfile: Containerfile
    depends_on:
      - elasticsearch
    env_file: .env
    volumes:
      - .:/workspace
    ports:
      - "${PORT}:${PORT}"
    profiles:
      - no-run

  elasticsearch:
    environment:
      - discovery.type=single-node
      - node.name=search_engine
      - xpack.security.enabled=false
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.11.3"
    env_file: .env
    ports:
      - "9200:${ELASTICSEARCH_HTTP_PORT}"
      - "9300:${ELASTICSEARCH_TRANSPORT_PORT}"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
